name: Custom deployment of my website
on: push
jobs:
  build-my-website:
     name: Build project
     runs-on: ubuntu-latest
     steps: 
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Install npm dependencies
       run: npm install
     - name: Build project assets
       run: npm run build
     
